apiVersion: apps/v1
kind: Deployment
metadata:
  name: appointment-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: appointment-app
  template:
    metadata:
      labels:
        app: appointment-app
    spec:
      containers:
        - name: appointment
          image: 282865065290.dkr.ecr.us-east-1.amazonaws.com/appointment
          imagePullPolicy: Always
          ports:
            - containerPort: 7000
          envFrom:
            - configMapRef:
                name: appointment
            - configMapRef:
                name: database
            - configMapRef:
                name: kafka
