apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-app
spec:
  replicas: 8
  selector:
    matchLabels:
      env: dev
      app: frontend
  template:
    metadata:
      labels:
        env: dev
        app: frontend
    spec:
      containers:
        - name: web
          image: nginx:alpine
