apiVersion: v1
kind: Service
metadata:
  name: svc-frontend
spec:
  type: NodePort
  selector:
    env: dev
    app: frontend
  ports:
    - nodePort: 30000
      port: 9000
      targetPort: 80
      protocol: TCP
