apiVersion: v1
kind: Secret
metadata:
  name: super-secret
type: Opaque
stringData:
  db_host: dev.host.local
  db_user: dev.user
  db_pass: dev.pass
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-app
spec:
  replicas: 1
  selector:
    matchLabels:
      env: dev
      app: frontend
  template:
    metadata:
      labels:
        env: dev
        app: frontend
    spec:
      containers:
        - name: web
          image: nginx:alpine
          env:
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: super-secret
                  key: db_host
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: super-secret
                  key: db_user
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: super-secret
                  key: db_pass
