post https://k8s-default-ingressa-d2bfbbe274-1094271374.us-east-1.elb.amazonaws.com/user
Content-Type: application/json

{
  "name": "Sergio",
  "lastname": "Hidalgo",
  "email": "sergio2@correo.com",
  "password": "12345",
  "roles": [{"roleId": "420315c8-9065-4fa2-be9d-c7093dc525c5"}, {"roleId": "530536bd-f325-40ee-8ca9-78d7d5ee149e"}]
}

###
get http://localhost:4000/user/80cf2852-cb77-45ae-beeb-834d69c2ceff

###
post http://localhost:4000/user/login
Content-Type: application/json

{
  "email": "sergio@correo.com",
  "password": "12345"
}
