apiVersion: apps/v1
kind: Deployment
metadata:
  name: appointment-mx-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: appointment-mx-app
  template:
    metadata:
      labels:
        app: appointment-mx-app
    spec:
      containers:
        - name: appointment-mx
          image: 282865065290.dkr.ecr.us-east-1.amazonaws.com/appointment-mx
          imagePullPolicy: Always
          ports:
            - containerPort: 8100
          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: appointment-co
                  key: PORT
            - name: APP_HOSTNAME
              valueFrom:
                configMapKeyRef:
                  name: appointment-co
                  key: APP_HOSTNAME
            - name: KAFKA_GROUP_ID
              valueFrom:
                configMapKeyRef:
                  name: appointment-co
                  key: KAFKA_GROUP_ID
            - name: KAFKA_TOPIC
              valueFrom:
                configMapKeyRef:
                  name: appointment-co
                  key: KAFKA_TOPIC

            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: database
                  key: DB_HOST
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: database
                  key: DB_PORT
            - name: DB_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: database
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: database
                  key: DB_PASSWORD
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: database
                  key: DB_NAME
            - name: DB_SYNCHRONIZE
              valueFrom:
                configMapKeyRef:
                  name: database
                  key: DB_SYNCHRONIZE
            - name: DB_LOGGING
              valueFrom:
                configMapKeyRef:
                  name: database
                  key: DB_LOGGING
            - name: DB_POOL_SIZE
              valueFrom:
                configMapKeyRef:
                  name: database
                  key: DB_POOL_SIZE
            - name: DB_MAX_QUERY_EXECUTION_TIME
              valueFrom:
                configMapKeyRef:
                  name: database
                  key: DB_MAX_QUERY_EXECUTION_TIME

            - name: KAFKA_CLIENT_ID
              valueFrom:
                configMapKeyRef:
                  name: kafka
                  key: KAFKA_CLIENT_ID
            - name: KAFKA_BROKERS
              valueFrom:
                configMapKeyRef:
                  name: kafka
                  key: KAFKA_BROKERS
            - name: KAFKA_TOPIC_APPOINTMENT
              valueFrom:
                configMapKeyRef:
                  name: kafka
                  key: KAFKA_TOPIC_APPOINTMENT
            - name: KAFKA_TOPIC_ROLLOUT
              valueFrom:
                configMapKeyRef:
                  name: kafka
                  key: KAFKA_TOPIC_ROLLOUT
# KAFKA_CLIENT_ID=my-client-kafka
# KAFKA_BROKERS=kafka:29092
# KAFKA_TOPIC_APPOINTMENT=appointment
# KAFKA_TOPIC_ROLLOUT=appointment-rollout
